create feat/setting
MeMindLab/Mobile pull request #12
Opened 2023-12-14 14:04 UTC by jeonhl7579

세팅화면
![image](https://github.com/MeMindLab/Mobile/assets/68419483/8afd3235-d7af-4fc8-8d3b-5352e42d14ce)
계정정보 - 진행중
![image](https://github.com/MeMindLab/Mobile/assets/68419483/ca0c2608-2b05-4638-9460-7300cd2028cc)

navBar 수정

2023-12-15 12:29 UTC, Luceta commented
pubpec.locks파일이 변경 되었는데, 로컬 버전의 상태과 다른거 같네요.. x code버전이 최신이 맞을까요? 변경되지 않아야 정상인데, x code버전 확인해주시고 pub update get, 둘 다 하시고 작업해주세요! 그래도 바뀌는 부분이 있다면 로컬 환경상태 때문이니 공유해주시길 바랍니다.

2023-12-15 12:54 UTC, Luceta commented
네브바도 만들어주시고 수고하셨습니다. 수정된 디자인에 맞춰서 그러면 네브바 작업해주시고 pr 올려주시면 그것으로 나중에 rootTab네브바를 대체하면 될것 같습니다. ( 기존 rootTab이 네브바이니 그거 보시고 변경된 네브바로 작업 해주셔도 될것 같아요. )

appBar는 제가 대체해서 올리겟습니다. 중복이나 컴포넌트화가 필요한 부분이 dialog쪽에서 보입니다.

2023-12-15 13:00 UTC, jeonhl7579 commented
제가 window환경에서 개발하다보니 xcode를 이요할 수 없어서 버전이 다른거 같습니다.

2023-12-15 13:12 UTC, Luceta commented
android adk 랑 스튜디오 버전이 몇일까요?  xcode이용 못하더라도 아마 Pub  로컬환경이 달라서 그런 것같네요. 한번 확인 해주세요,

2023-12-15 13:37 UTC, jeonhl7579 commented
안드로이드 스튜디오 버전 : Runtime version: 17.0.6+0-b2043.56-10027231 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
android sdk는 34인거 같습니다.

2023-12-16 13:41 UTC, jeonhl7579 commented
세팅화면 수정했습니다.
![image](https://github.com/MeMindLab/Mobile/assets/68419483/4245beb8-e29d-4205-9d30-37da51cdf758)
의견보내기 페이지 사진 갤러리에서 추가하게 했습니다.
![image](https://github.com/MeMindLab/Mobile/assets/68419483/af94adc1-883c-4d77-9db6-7c18ef2d82ba)

2023-12-16 15:07 UTC, Luceta commented
의견 보내기 스샷보니 디자인 시안이랑 달라보여요!  보더 확인해주시고,  버튼은 roundedButton 컴포넌트 쓰시고 디자인 시안 다시 확인 부탁드립니다! 세팅 화면에서 아래  배경이 네브바만 하늘색이던데 이건 왜 그런지 한번 확인해주세요!

2023-12-18 11:22 UTC, Luceta commented on lib/settings/view/s_setting.dart
>  class Setting extends StatefulWidget {
Settings로 복수로 해도 좋을 것 같습니다.

2023-12-18 11:22 UTC, Luceta commented on lib/settings/view/s_setting_userinfo.dart
> +                            SeetingCustomTextFormField(
이 부분 새로 만드신것 같아서 common 에 component에 custom Text form있어서 그 부분 활용해서 해주시면 될 것 같습니다 !  
원래 있던 부분 props추가 하거나 Extends 하셔서 하시면 될 것 같아요 .

2023-12-18 11:22 UTC, Luceta commented on lib/settings/component/settings_dialog.dart
> +      width: 190,
이 컴포넌트는 어느 쪽에 쓰이는걸까요?  190 , 41 과 75,41로 이루어져있는데 어던 부분인지 확인이 어렵네요. 
매직 상수보다는 변수명을 활용하는 부분이 더 좋을 것 같습니다. 왜 141 인지..

혹시 로그아웃 뜨는 다이얼로그 화면이라면 왜 status인지 여쭤봐도 될까요? statlessd위젯 컴포넌트로 props하고 액션 함수만 넘겨주는 형식으로 하면될 것 같아보여서요

2023-12-18 11:22 UTC, Luceta commented on lib/settings/component/settings_dialog.dart
> +      width: 190,
다이알로그르  default로 취소 확인이 잇는 형식으로 만들어 놓고,  width / height props로 받되 기본 초기값을 정해주면 될 것 같습니다.  onlyConfirm 아니면 cancel 같은 bool변수를 만들어서 그거 여부에 따라서 아래 버튼 여부를 1개일지 2개로 분리하면 좋을 것 같습니다.

2023-12-18 11:22 UTC, Luceta commented on lib/settings/component/settings_menu.dart
> +  }) : super(key: key);
혹시 이 부분은 구지 key? 와 super(key:key) 로 키가 있을시로 해준 이유가 있을까요?
null safety적용된 이후로는  아래처럼 해도 되는 것으로 알고 있습니다. ,

 ```
const SettingMenu({
   super.key,
    required this.height,
    required this.content,
    required this.subscribe,
  });
```

2023-12-18 11:22 UTC, Luceta commented on lib/settings/view/s_setting.dart
> +      child: Container(
이거 아마 conTainer 위젯으로 사용시,  decoration없으면 린트에서 워닝뜰텐데 한번 확인해주세요! 없어도 CONTAINER 없어도 
될듯합니다. 

Column위젯에 패딩만 넣어줘도 아마 동일하게 나올 것 같습니다.

2023-12-18 11:22 UTC, Luceta commented on lib/settings/component/settings_custom_text_form.dart
> +    this.obscureText = false,
혹시 이 부분은 props가 optional이 아닌데
 required가 아니고 초기값을 할당해준 이유가 무엇일까요?

2023-12-18 11:22 UTC, Luceta commented on lib/settings/view/s_setting_userinfo.dart
> +                        text: "가입하기",
텍스트가 수정인 것 같습니다 피그마 확인해주시면 감사합니다.

2023-12-18 11:22 UTC, Luceta commented on lib/settings/view/s_setting_userinfo.dart
> +    // return DefaultLayout(
아래 주석 코드는 사용되어 있지 않는데 개발도중에 작성하신거라면 pr올릴때는 지우시고 올려주세요.

2023-12-18 11:22 UTC, Luceta commented on lib/common/theme/custom_theme_app.dart
> +  late CustomTheme theme = CustomTheme.light ?? systemTheme;
이 부분은  아래처럼 변경하면 될 거 같습니다. 추후에 확작성을 고려해서 
나중에 다시 다크로 변경하는 확장성을 위해서 default Theme 을 변경가능하게 한 의도였습니다. 혹시 바꾼 이유가 있을까요 ?
`  late CustomTheme theme =
      App.defaultTheme ?? systemTheme; //디폴트를 주시거나, 시스템을 따라가게 합니다.

  final CustomTheme? defaultTheme = CustomTheme.light;`

2023-12-18 11:22 UTC, Luceta commented on lib/settings/view/s_setting.dart
> +    final settingmenus = ['FAQ', '이용 약관', '개인정보 처리방침'];
요거는 현재 사용되지 않는 변수 인것 같은데  리팩토링 중이신 걸까요 ?

2023-12-18 11:22 UTC, Luceta commented on pubspec.yaml
>  dependencies:
디펜던시가 전부 하나로 합쳐져 있던데, 임의로 수정하신건가요?  

기존에 기능별로 협업시나 혹은 어떤 라이브러리를 확인을 서로 하기 위해서 주석과 함께 분리해놨는데 , 합쳐져 있습니다. 
확인해주시면 좋을 것 같습니다.

2023-12-18 11:22 UTC, Luceta commented on lib/settings/component/settings_custom_text_form.dart
> +    this.obscureText = false,
@jeonhl7579 아직 코멘트가 없어서 ..보시라고 남겨봅니다.

2023-12-18 11:22 UTC, Luceta commented on lib/settings/component/certified_box.dart
> +  bool certi;
개인적인 의견으론 변수가 길지 않으니 명시적으로  `bool isCertified `이런 식으로 표기해주면 좋을 것 같아 보입니다.

2023-12-18 11:22 UTC, Luceta commented on lib/settings/component/certified_box.dart
> +    Key? key,
이 부분 코멘트 달았는데 답변이 없어서 궁금하네요. 🧐

2023-12-18 11:22 UTC, Luceta commented on lib/settings/component/certified_box.dart
> +        child: const Center(
이것은 나중에 추후 리팩토링시 fontSizes클래스 참조해주시면 좋을 것 같습니다

2023-12-18 11:36 UTC, jeonhl7579 commented on lib/settings/view/s_setting.dart
> +    final settingmenus = ['FAQ', '이용 약관', '개인정보 처리방침'];
이부분은 설정페이지에서 FAQ, 이용약관, 개인정보 처리방침 메뉴 부분을 Listview.seperated 통해서 사용중인 변수입니다.

2023-12-18 13:01 UTC, jeonhl7579 commented on lib/settings/component/settings_custom_text_form.dart
> +    this.obscureText = false,
그 부분은 기존 common 폴더의 custom_text_form 파일을 그대로 복사해서 그런거 같습니다.

2023-12-18 13:03 UTC, jeonhl7579 commented
계정정보 페이지 추가
![image](https://github.com/MeMindLab/Mobile/assets/68419483/79a4d1ab-4f38-400f-834b-660c1191d3df)

2023-12-19 06:42 UTC, Luceta requested changes
폰트 사이즈 관련등 코멘트 다시 확인해주시면 감사합니다.

2023-12-19 06:42 UTC, Luceta commented on lib/common/component/custom_dialog.dart
>                      style: const TextStyle(
텍스트 관련 모든 사용하는 곳에서 fontsizes 클래스로 가져와서 색상값만 넣어서 해주시면 좋을 것 같습니다. 저번에 언급했는데 못보신것 같아서 다시 남겨봅니다.

2023-12-19 06:42 UTC, Luceta commented on lib/settings/component/certified_box.dart
> +        child: const Center(
여기도 위에 말한코멘트 그대로 있습니다 확인해주세요.

2023-12-19 06:46 UTC, Luceta reviewed
칼라 ,폰트 관련과

2023-12-19 06:46 UTC, Luceta commented on lib/common/component/custom_dialog.dart
>                      style: const TextStyle(
h3 : 칼라도 app Colors를 직접 가져다 쓰는게 아니라 테마에서 꺼내쓰시면 될 것 같습니다. 이 부분도 수정해주시면 좋을 것 같아요.

2023-12-19 06:46 UTC, Luceta commented on lib/settings/component/settings_custom_text_form.dart
> +              color: AppColors.gray9,
이것도 위에처럼 명시적으로 테마에서 가져다가 hint Text칼라로 하면 되는데 gray9으로 바꾸셧네요! 
hintTextColor. 테마 폴더가시면 라이트 테마에 이미 gray9으로 셋팅되어있습니다. 다시 확인해주세요 .

2023-12-19 06:49 UTC, Luceta commented on lib/settings/view/s_setting.dart
> +                    CertifiedBox(isCertified: true),
저 컴포넌트에서 기본값을 false로 해놓고 있을때만 true주는 식으로 하면 될것 같습니다.

2023-12-19 06:55 UTC, Luceta commented on lib/settings/component/certified_box.dart
> +    if (isCertified == false) {
보통 요 부분은 if분기물 할때 true일 때로 나누니 특별한 로직이 아니고 ui적인 것 같으면
개인적으로는  if (isCertifie) true로 분기로 해주시면 좋을 것 같습니다.
h4 : 분기 나뉘는게 color와 text만 다르므로  요런식으로 변수로 주고 , 리팩토링하면 구지 if문을 안해도 될 것 같습니다. 예시입니다.
```
    final containerWidth = isCertified ? 65.0 : 52.0;
    final text = isCertified ? "인증완료" : "미인증";

    return Container(
      width: containerWidth,
      height: 21,
      margin: const EdgeInsets.only(left: 10),
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(10),
        color: isCertified
            ? const Color.fromRGBO(255, 238, 151, 1)
            : const Color.fromRGBO(204, 204, 204, 1),
      ),
      child: Center(
        child: Text(
          text,
          style: TextStyle(fontSize: 12, color: AppColors.blue8),
        ),
      ),
```

2023-12-19 06:58 UTC, Luceta commented on lib/settings/view/s_setting_userinfo.dart
> +  void _startTimer() {
h5: 요거는 추후에 나중에라도 타이머가 다른데도 쓰인다면 유틸로 공용으로 빼서 사용해도 될듯합니다.

2023-12-19 06:58 UTC, Luceta commented on lib/settings/view/s_setting_userinfo.dart
> +                                          backgroundColor: AppColors.yellow,
h2:모든 color 스타일에서 다 color직접인 아닌 테마에서 꺼내쓰는형식으로 바꿔주시면 좋을 것 같습니다.

2023-12-19 07:18 UTC, jeonhl7579 commented on lib/settings/view/s_setting.dart
> +                    CertifiedBox(isCertified: true),
넵 수정했습니다.

2023-12-19 07:22 UTC, jeonhl7579 commented on lib/settings/component/certified_box.dart
> +    if (isCertified == false) {
반영했습니다.

2023-12-19 07:25 UTC, jeonhl7579 commented on lib/settings/view/s_setting_userinfo.dart
> +                                          backgroundColor: AppColors.yellow,
테마에서 꺼내 쓸때 yellow같이 없는 애들은 어떻게 할까요

2023-12-19 07:31 UTC, Luceta commented on lib/settings/view/s_setting_userinfo.dart
> +                                          backgroundColor: AppColors.yellow,
dev에 테마색잇는데 그 부분 확인해주세요.

2023-12-19 08:50 UTC, merged